# Generated by Django 4.0.3 on 2023-08-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_followers_remove_profile_following_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followlist',
            unique_together={('follower', 'following')},
        ),
    ]
