# Generated by Django 4.0.3 on 2023-09-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_followlist_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followlist',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='creation_date',
        ),
    ]
