# Generated by Django 4.0.3 on 2023-09-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_followlist_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followlist',
            old_name='status',
            new_name='reqstatus',
        ),
    ]
