# Generated by Django 4.2.4 on 2023-08-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_or_phone',
            field=models.CharField(default=9898982334, max_length=50),
            preserve_default=False,
        ),
    ]
